# Generated by Django 4.2.5 on 2023-09-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='creator',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Тип1', 'Общее'), ('Тип2', 'Не зачислен платеж'), ('Тип3', 'Запрос закрывающих документов')], default='Тип1', max_length=10, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
