# Generated by Django 4.2.5 on 2023-09-15 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_remove_file_task_rename_creator_task_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('низкая', 'Низкая'), ('средняя', 'Средняя'), ('высокая', 'Высокая')], default='низкая', max_length=50, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='region',
            field=models.CharField(choices=[('регион1', 'Республика Адыгея'), ('регион2', 'Республика Алтай'), ('регион3', 'Алтайский край'), ('регион4', 'Амурская область'), ('регион5', 'Архангельская область'), ('регион6', 'Астраханская область')], default='регион1', max_length=100, verbose_name='Регион*'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Тип1', 'Общее'), ('Тип2', 'Не зачислен платеж'), ('Тип3', 'Запрос закрывающих документов')], default='Тип1', max_length=10, verbose_name='Тип задачи*'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
