# Generated by Django 4.2.5 on 2023-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_comment_created_at_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
