# Generated by Django 4.2.5 on 2023-09-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_comments_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_number',
        ),
    ]
