# Generated by Django 4.2.5 on 2023-09-16 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_remove_task_task_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('Тип1', 'Общее'), ('Тип2', 'Не зачислен платеж'), ('Тип3', 'Запрос закрывающих документов')], default='Тип1', max_length=10, verbose_name='Тип задачи*')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Файл')),
                ('importance', models.CharField(choices=[('низкая', 'Низкая'), ('средняя', 'Средняя'), ('высокая', 'Высокая')], default='низкая', max_length=50, verbose_name='Важность')),
                ('region', models.CharField(choices=[('регион1', 'Республика Адыгея'), ('регион2', 'Республика Алтай'), ('регион3', 'Алтайский край'), ('регион4', 'Амурская область'), ('регион5', 'Архангельская область'), ('регион6', 'Астраханская область')], default='регион1', max_length=100, verbose_name='Регион*')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('в ожидании', 'В ожидании'), ('в процессе', 'В процессе'), ('завершено', 'Завершено')], default='в ожидании', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'historical task',
                'verbose_name_plural': 'historical tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
